import React from 'react'

const Homepage = () => {
  return (
    <>
    
        <section id='Home'>
            <h2>Home section</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />
            </p>
        </section>

        <section id='About'>
            <h2>About section</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />
            </p>
        </section>

        <section id='Contact'>
            <h2>Contact section</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis iste repellendus vitae voluptatum atque dignissimos tempore sit quos quaerat dolore, quod suscipit expedita. Dignissimos laudantium officiis ratione laboriosam ex cum ipsam nemo obcaecati et optio quisquam vitae id minus ipsum asperiores impedit, totam deleniti cupiditate labore saepe non. Enim commodi sed, voluptatum mollitia excepturi, minima iusto delectus provident eaque quisquam est, vitae id. Iusto cupiditate mollitia, aliquid ipsa veniam eaque excepturi id dicta numquam totam voluptatibus natus aut est. Accusantium quia libero sunt totam dolorem, commodi mollitia nostrum doloremque praesentium. Error nobis ab obcaecati eum sapiente! Explicabo tempora a placeat quibusdam est, consectetur ea hic impedit provident aliquam doloremque blanditiis dolores, dolore enim adipisci ad voluptate ducimus iusto exercitationem nam cumque! Hic sapiente, ducimus sint tempora consequatur pariatur commodi minus laboriosam quo fuga officiis, dolore, maxime temporibus vel quaerat laudantium eveniet illum voluptates eos facere vitae veniam! Reiciendis minima odio expedita dolor architecto? Dignissimos nihil fugiat excepturi eaque adipisci ducimus consectetur dolore nisi animi necessitatibus quisquam quis neque mollitia, ipsam minima praesentium quia voluptatum. Placeat tempora rem nostrum quod quaerat tenetur in rerum modi, saepe adipisci? Veniam, vero beatae! Mollitia quia culpa iure. Numquam obcaecati aliquid deserunt! Reiciendis, quasi totam?
                <br />
            </p>
        </section>
    
    </>
  )
}

export default Homepage